name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate analysis

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'  # You can change this to another distribution if needed

      # Step 3: Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Step 4: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 5: Build the project and run SonarQube analysis
      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for PR info
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Build the project and run SonarQube analysis
          mvn clean verify sonar:sonar \
            -Dsonar.host.url=https://your-sonarqube-server.com  # If using a custom SonarQube server
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # Authentication token for SonarQube
            -Dsonar.projectKey=hrdOrg_Soft_project  # Your SonarQube project key
            -Dsonar.projectName="HRD Soft Project"  # Name of your project in SonarQube
            -Dsonar.coverage.exclusions=**/main.java  # Exclude specific files from coverage analysis
            -Dsonar.java.binaries=target/classes  # Ensure SonarQube knows where the compiled classes are

          # Optionally, you can specify JaCoCo report path if needed for better coverage analysis
          -Dsonar.jacoco.reportPaths=target/jacoco.exec  # Path to JaCoCo coverage report
